sonar.exclusions=database/**,**/node_modules/**,**/venv/**,**/env/**
# Configuration principale
sonar.projectKey=Bertrand2808_FreelanSign
sonar.organization=freelansign546874684
sonar.projectName=FreelanSign

# Exclusions globales
sonar.exclusions=database/**,**/node_modules/**,**/venv/**,**/env/**


# Configuration des modules
sonar.modules=backend,frontend

# Configuration Backend (Django)
backend.sonar.projectName=Backend Django
backend.sonar.sources=.
backend.sonar.exclusions=**/migrations/**,**/venv/**,**/env/**,**/__pycache__/**,**/static/**,**/media/**
backend.sonar.python.coverage.reportPaths=coverage.xml
backend.sonar.python.xunit.reportPath=test-results.xml

# Configuration Frontend (Vue)
frontend.sonar.projectName=Frontend Vue
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.js,**/*.test.js
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
frontend.sonar.typescript.lcov.reportPaths=coverage/lcov.info
