# Generated by Django 5.2.4 on 2025-12-03 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quote", "0008_alter_quote_account"),
        ("user", "0012_add_rate_and_service_types_to_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalTemplateModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("jurisdiction", models.CharField(default="FR", max_length=10)),
                ("version", models.CharField(max_length=50)),
                ("clauses", models.JSONField(help_text="List of clause objects with default content")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "legal_template",
                "indexes": [models.Index(fields=["jurisdiction", "is_active"], name="legal_templ_jurisdi_4a1c4d_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("jurisdiction", "version"), name="unique_jurisdiction_version")
                ],
            },
        ),
        migrations.CreateModel(
            name="AttachedTermsModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("template_version", models.CharField(max_length=50)),
                ("rendered_html", models.TextField()),
                ("rendered_text", models.TextField()),
                ("snapshot_data", models.JSONField(help_text="Complete snapshot of terms at creation")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="legal_terms", to="quote.quote"
                    ),
                ),
            ],
            options={
                "db_table": "attached_terms",
                "indexes": [models.Index(fields=["quote"], name="attached_te_quote_i_74bca9_idx")],
            },
        ),
        migrations.CreateModel(
            name="LegalProfileModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("clause_overrides", models.JSONField(default=dict, help_text="Overrides by clause identifier")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="legal_profile", to="user.account"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="legal_terms.legaltemplatemodel",
                    ),
                ),
            ],
            options={
                "db_table": "legal_profile",
                "indexes": [models.Index(fields=["account"], name="legal_profi_account_752675_idx")],
            },
        ),
    ]
