# Generated by Django 5.2.4 on 2025-12-03 15:14

import uuid

from django.db import migrations


def seed_base_fr_template(apps, schema_editor):
    """Seed initial FR legal template v1.0.0."""
    LegalTemplateModel = apps.get_model("legal_terms", "LegalTemplateModel")

    # Create base FR template
    LegalTemplateModel.objects.create(
        id=uuid.uuid4(),
        name="CGV Auto-Entrepreneur FR",
        jurisdiction="FR",
        version="1.0.0",
        clauses=[
            {
                "identifier": "payment_terms",
                "category": "mandatory",
                "default_title": "Conditions de paiement",
                "default_body": (
                    "Le paiement est dû sous 30 jours à compter de la date d'émission "
                    "de la facture. Les paiements peuvent être effectués par virement "
                    "bancaire ou chèque à l'ordre de {{BUSINESS_NAME}}. "
                    "En cas de retard de paiement, des pénalités de retard égales à trois "
                    "fois le taux d'intérêt légal seront appliquées, ainsi qu'une indemnité "
                    "forfaitaire pour frais de recouvrement de 40 euros."
                ),
                "default_order": 1,
                "default_is_active": True,
                "help_text": "Conditions de règlement et pénalités de retard (obligatoire)",
            },
            {
                "identifier": "service_delivery",
                "category": "mandatory",
                "default_title": "Modalités d'exécution de la prestation",
                "default_body": (
                    "Les prestations seront exécutées conformément aux modalités définies "
                    "dans le devis accepté. Le prestataire s'engage à mettre en œuvre tous "
                    "les moyens nécessaires à la bonne réalisation des services convenus. "
                    "Les délais indiqués sont donnés à titre indicatif et leur dépassement "
                    "ne saurait donner lieu à indemnité ou pénalité."
                ),
                "default_order": 2,
                "default_is_active": True,
                "help_text": "Modalités d'exécution de la prestation (obligatoire)",
            },
            {
                "identifier": "liability",
                "category": "mandatory",
                "default_title": "Responsabilité",
                "default_body": (
                    "{{BUSINESS_NAME}} ne saurait être tenu responsable des dommages "
                    "indirects, immatériels ou consécutifs, tels que notamment les pertes "
                    "de données, de bénéfices, de chiffre d'affaires ou d'exploitation. "
                    "La responsabilité du prestataire est limitée au montant de la prestation "
                    "facturée. Le prestataire n'est pas responsable des retards ou inexécutions "
                    "dus à un cas de force majeure."
                ),
                "default_order": 3,
                "default_is_active": True,
                "help_text": "Limitation de responsabilité (obligatoire)",
            },
            {
                "identifier": "intellectual_property",
                "category": "mandatory",
                "default_title": "Propriété intellectuelle",
                "default_body": (
                    "Les documents, créations, méthodes et savoir-faire développés par "
                    "{{BUSINESS_NAME}} dans le cadre de cette prestation restent sa propriété "
                    "exclusive, sauf stipulation contraire dans le devis. Le client bénéficie "
                    "d'un droit d'usage des livrables pour les besoins de son activité, "
                    "dans les limites définies contractuellement."
                ),
                "default_order": 4,
                "default_is_active": True,
                "help_text": "Droits de propriété intellectuelle (obligatoire)",
            },
            {
                "identifier": "termination",
                "category": "optional",
                "default_title": "Résiliation",
                "default_body": (
                    "En cas de manquement grave de l'une des parties à ses obligations, "
                    "le contrat pourra être résilié de plein droit 15 jours après mise en "
                    "demeure restée sans effet. La résiliation n'affecte pas les sommes "
                    "dues au titre des prestations déjà réalisées."
                ),
                "default_order": 5,
                "default_is_active": True,
                "help_text": "Conditions de résiliation (optionnel)",
            },
            {
                "identifier": "confidentiality",
                "category": "optional",
                "default_title": "Confidentialité",
                "default_body": (
                    "Les parties s'engagent à garder confidentielles toutes les informations "
                    "de nature confidentielle dont elles auraient connaissance dans le cadre "
                    "de l'exécution du contrat. Cette obligation de confidentialité survivra "
                    "à l'expiration ou à la résiliation du contrat pour une durée de 5 ans."
                ),
                "default_order": 6,
                "default_is_active": False,
                "help_text": "Clause de confidentialité (optionnel, inactive par défaut)",
            },
            {
                "identifier": "warranty",
                "category": "optional",
                "default_title": "Garantie",
                "default_body": (
                    "Le prestataire garantit la conformité des prestations réalisées pendant "
                    "une durée de 3 mois à compter de la livraison. Cette garantie est limitée "
                    "à la correction des vices cachés et non-conformités signalés par écrit "
                    "dans ce délai."
                ),
                "default_order": 7,
                "default_is_active": True,
                "help_text": "Garantie sur les prestations (optionnel)",
            },
            {
                "identifier": "applicable_law",
                "category": "mandatory",
                "default_title": "Droit applicable et juridiction",
                "default_body": (
                    "Le présent contrat est soumis au droit français. En cas de litige, "
                    "et à défaut d'accord amiable, les tribunaux français seront seuls compétents. "
                    "Siège social: {{ADDRESS}} - SIRET: {{SIRET}} - Email: {{EMAIL}} - "
                    "Téléphone: {{PHONE}}"
                ),
                "default_order": 8,
                "default_is_active": True,
                "help_text": "Loi applicable et mentions légales (obligatoire)",
            },
        ],
        is_active=True,
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded template."""
    LegalTemplateModel = apps.get_model("legal_terms", "LegalTemplateModel")
    LegalTemplateModel.objects.filter(
        jurisdiction="FR", version="1.0.0", name="CGV Auto-Entrepreneur FR"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("legal_terms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_base_fr_template, reverse_seed),
    ]
