# Generated by Django 5.2.4 on 2025-12-11 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("account_created", "Compte créé"),
                            ("account_deleted", "Compte supprimé"),
                            ("account_anonymized", "Compte anonymisé"),
                            ("client_created", "Client créé"),
                            ("client_deleted", "Client supprimé"),
                            ("client_anonymized", "Client anonymisé"),
                            ("quote_sent", "Devis envoyé"),
                            ("quote_signed", "Devis signé"),
                            ("payment_received", "Paiement reçu"),
                            ("data_export_requested", "Export de données demandé"),
                            ("data_deletion_requested", "Suppression de données demandée"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Nom logique de la ressource ciblée (ex: Account, Client, etc).", max_length=64
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="Identifiant de la ressource ciblée (UUID, int, etc. sérialisé en string).", max_length=64
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données contextuelles minimales (attention à ne pas mettre de données sensibles inutiles).",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP de l'acteur si action initiée via HTTP.", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Utilisateur à l'origine de l'action (peut être null si script / tâche async).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["actor", "timestamp"], name="core_audit__actor_i_2870ae_idx"),
                    models.Index(fields=["target_model", "target_id"], name="core_audit__target__a02965_idx"),
                    models.Index(fields=["action", "timestamp"], name="core_audit__action_1cc579_idx"),
                ],
            },
        ),
    ]
