# Generated by Django 5.2.4 on 2026-02-08 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[("BUG", "Bug"), ("SUGGESTION", "Suggestion"), ("QUESTION", "Question"), ("KUDOS", "Kudos")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("page_url", models.URLField(blank=True, default="", max_length=500)),
                ("app_version", models.CharField(blank=True, default="", max_length=50)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
