# Generated by Django 5.2.4 on 2025-08-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Nom de l'area")),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120, verbose_name="Nom de la prestation")),
                ("description", models.TextField(blank=True, verbose_name="Description de la prestation")),
                (
                    "weight_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Durée moyenne en jours pour exécuter la prestation.",
                        verbose_name="Jours-homme moyens (entier)",
                    ),
                ),
                (
                    "default_rate_cents",
                    models.BigIntegerField(
                        default=0,
                        help_text="Exemple: 120000 pour 1200.00€",
                        verbose_name="Tariff unique par prestation (en centimes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Brouillon"), ("ACTIVE", "Active"), ("ARCHIVED", "Archivée")],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut de la prestation",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="prestations", to="catalog.area"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation",
                "verbose_name_plural": "Prestations",
                "ordering": ("area__name", "name"),
                "indexes": [models.Index(fields=["area", "status"], name="idx_prest_area_status")],
                "constraints": [
                    models.UniqueConstraint(fields=("area", "name"), name="unique_area_prestation_name"),
                    models.CheckConstraint(condition=models.Q(("weight_days__gte", 0)), name="prestation_weight_days_nonneg"),
                    models.CheckConstraint(condition=models.Q(("default_rate_cents__gte", 0)), name="prestation_rate_nonneg"),
                ],
            },
        ),
    ]
