# Generated by Django 5.2.4 on 2025-09-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("user", "0007_professionaluser_allowed_areas"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prestation",
            name="unique_area_prestation_name",
        ),
        migrations.AddField(
            model_name="prestation",
            name="custom",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si la prestation a été ajoutée par un professionel (non partagée globalement).",
                verbose_name="Custom",
            ),
        ),
        migrations.AddField(
            model_name="prestation",
            name="professional_user",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, indicates which professional created this custom prestation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_prestations",
                to="user.professionaluser",
            ),
        ),
        migrations.AddIndex(
            model_name="prestation",
            index=models.Index(fields=["professional_user"], name="idx_prest_professional_user"),
        ),
        migrations.AddConstraint(
            model_name="prestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("professional_user__isnull", True)),
                fields=("area", "name"),
                name="unique_area_prestation_name_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="prestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("professional_user__isnull", False)),
                fields=("professional_user", "name"),
                name="unique_professional_prestation_name",
            ),
        ),
    ]
