# Generated by Django 5.2.4 on 2025-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_account_not_null_drop_professional_user"),
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        # Use raw SQL to avoid field resolution issues
        migrations.RunSQL(
            sql="ALTER TABLE catalog_prestation DROP CONSTRAINT IF EXISTS unique_area_prestation_name_global;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="prestation",
            constraint=models.UniqueConstraint(
                condition=models.Q(account__isnull=True),
                fields=("area", "name"),
                name="unique_area_prestation_name_global",
            ),
        ),
    ]
