# Generated by Django 5.2.4 on 2025-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_prestation_unique_area_prestation_name_global_and_more"),
    ]

    operations = [
        # State-only: Remove old constraint definition from migration state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # DB already correct, no-op
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="prestation",
                    name="unique_area_prestation_name_global",
                ),
                migrations.AddConstraint(
                    model_name="prestation",
                    constraint=models.UniqueConstraint(
                        fields=["area", "name"],
                        condition=models.Q(account__isnull=True),
                        name="unique_area_prestation_name_global",
                    ),
                ),
            ],
        ),
    ]
