# Generated by Django 5.2.4 on 2025-10-29 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandTheme",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the theme (e.g. 'Default', 'Professional', 'Personal').", max_length=128
                    ),
                ),
                ("is_active", models.BooleanField(default=False, help_text="Whether the theme is active.")),
                (
                    "colors",
                    models.JSONField(
                        default=dict,
                        help_text="Color palette: primary, secondary, background, text_primary, text_secondary, border, highlight.",
                    ),
                ),
                (
                    "typography",
                    models.JSONField(
                        default=dict, help_text="Typography config: heading_font, body_font, font_sizes, line_heights."
                    ),
                ),
                (
                    "spacing",
                    models.JSONField(default=dict, help_text="Spacing config: page_margin, section_spacing, element_padding."),
                ),
                (
                    "logo",
                    models.FileField(blank=True, help_text="Logo image file.", null=True, upload_to="branding/logos/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        help_text="Professional user who owns the theme.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Theme",
                "verbose_name_plural": "Brand Themes",
                "db_table": "branding_brand_theme",
                "ordering": ["-is_active", "-updated_at"],
                "indexes": [
                    models.Index(fields=["professional", "is_active"], name="ix_brand_professional_active"),
                    models.Index(fields=["professional"], name="ix_brand_professional"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("professional", "name"), name="uq_brand_professional_name"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)), fields=("professional",), name="uq_brand_professional_active"
                    ),
                ],
            },
        ),
    ]
