# Generated by Django 5.2.4 on 2025-11-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account owning this client.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="user.account",
            ),
        ),
    ]
