# Generated by Django 5.2.4 on 2025-11-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_migrate_client_to_account"),
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="account",
            field=models.ForeignKey(
                help_text="Account owning this client.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="user.account",
            ),
        ),
    ]
