# Generated by Django 5.2.4 on 2025-11-30 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_client_account"),
        ("user", "0010_migrate_professional_to_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="client",
            name="ix_client_owner_name",
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["account", "name"], name="ix_client_account_name"),
        ),
    ]
