# Generated by Django 5.2.4 on 2025-12-11 07:38

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_add_soft_delete_to_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=apps.core.fields.EncryptedEmailField(blank=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="vat_number",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
    ]
