# Generated by Django 5.2.4 on 2026-01-02 16:43

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_add_field_encryption"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address_line1",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="address_line2",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="company",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="client",
            name="postal_code",
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
    ]
