# Generated by Django 5.2.4 on 2026-01-02 16:43

from django.db import migrations


def migrate_address_forward(apps, schema_editor):
    """Migrate legacy address field to structured fields."""
    Client = apps.get_model('client', 'Client')

    for client in Client.objects.all():
        # Extract country from metadata (used by quote tests as workaround)
        if client.metadata and 'country' in client.metadata:
            client.country = client.metadata['country'][:2].upper() if client.metadata['country'] else ''

        # Migrate legacy address field
        if client.address:
            # Split multi-line address: first line -> address_line1, rest -> address_line2
            lines = client.address.split('\n', 1)
            client.address_line1 = lines[0][:255] if lines else ''
            if len(lines) > 1:
                client.address_line2 = lines[1][:255]

        client.save(update_fields=['country', 'address_line1', 'address_line2'])


def migrate_address_reverse(apps, schema_editor):
    """Reconstruct legacy address from structured fields."""
    Client = apps.get_model('client', 'Client')

    for client in Client.objects.all():
        # Reconstruct legacy address field from structured fields
        parts = []
        if client.company:
            parts.append(client.company)
        if client.address_line1:
            parts.append(client.address_line1)
        if client.address_line2:
            parts.append(client.address_line2)
        if client.postal_code or client.city:
            city_line = f"{client.postal_code or ''} {client.city or ''}".strip()
            if city_line:
                parts.append(city_line)
        if client.country:
            parts.append(client.country)

        client.address = '\n'.join(p for p in parts if p)

        # Store country back in metadata for backward compatibility
        if client.country and client.metadata is not None:
            client.metadata['country'] = client.country

        client.save(update_fields=['address', 'metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_add_structured_address"),
    ]

    operations = [
        migrations.RunPython(migrate_address_forward, migrate_address_reverse),
    ]
