from typing import Iterable, Optional, Protocol


class ClientRepository(Protocol):
    def create(self, data: dict) -> object: ...
    def update(self, client_id: str, data: dict) -> object: ...
    def get_by_id(self, client_id: str) -> Optional[object]: ...
    def list(self, owner_id: Optional[int], search: Optional[str], ordering: Optional[str]) -> Iterable[object]: ...
    def delete(self, client_id: str) -> None: ...
