# Generated by Django 5.2.4 on 2025-09-20 14:30

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerms",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Short label, e.g. 'Net 30'.", max_length=128)),
                ("days", models.PositiveIntegerField(help_text="Number of days to add to issue_date.")),
                ("description", models.TextField(blank=True, help_text="Optional internal description.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner of these payment terms.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_terms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment terms",
                "verbose_name_plural": "Payment terms",
                "db_table": "quote_payment_terms",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("reference", models.CharField(help_text="Human-readable reference unique per owner.", max_length=64)),
                ("currency", models.CharField(help_text="ISO currency code, e.g. 'EUR'.", max_length=3)),
                ("language", models.CharField(default="fr", help_text="IETF language tag, e.g. 'fr', 'en'.", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "payment_terms_text",
                    models.CharField(
                        blank=True, help_text="Optional free-text payment terms if not using a template.", max_length=255
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Sum of line pre-tax totals.", max_digits=12
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Sum of taxes for the quote.", max_digits=12
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Global discount applied to the quote.",
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Expected: subtotal + tax_total - discount_total.",
                        max_digits=12,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="quotes/%Y/%m/")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client associated with this quote.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="client.client",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Quote owner (user/professional).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_terms",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to predefined payment terms.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="quote.paymentterms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "db_table": "quote_quote",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload_snapshot", models.JSONField(blank=True, default=dict, help_text="Light snapshot for traceability.")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("sent", "Sent"),
                            ("status_changed", "Status changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Related quote.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="quote.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote history",
                "verbose_name_plural": "Quote history",
                "db_table": "quote_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLineItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pre-tax total; computed on save().",
                        max_digits=12,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, help_text="Display order within the quote.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Owning quote.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quote.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote line item",
                "verbose_name_plural": "Quote line items",
                "db_table": "quote_line_item",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentterms",
            index=models.Index(fields=["owner", "name"], name="ix_paymentterms_owner_name"),
        ),
        migrations.AddConstraint(
            model_name="paymentterms",
            constraint=models.UniqueConstraint(fields=("owner", "name"), name="uq_paymentterms_owner_name"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["owner", "reference"], name="ix_quote_owner_reference"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="ix_quote_status"),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(fields=("owner", "reference"), name="uq_quote_owner_reference"),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(models.F("subtotal"), "+", models.F("tax_total")),
                            "-",
                            models.F("discount_total"),
                        ),
                    )
                ),
                name="ck_quote_totals_match",
            ),
        ),
        migrations.AddIndex(
            model_name="quotehistory",
            index=models.Index(fields=["quote", "timestamp"], name="ix_qhistory_quote_ts"),
        ),
        migrations.AddIndex(
            model_name="quotehistory",
            index=models.Index(fields=["action"], name="ix_qhistory_action"),
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(fields=["quote", "order"], name="ix_qlitem_quote_order"),
        ),
    ]
