# Generated by Django 5.2.4 on 2025-09-20 16:57

import django.core.validators
import django.db.models.expressions
import django.db.models.functions.comparison
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
        ("quote", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotelineitem",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="quote",
            name="ck_quote_totals_match",
        ),
        migrations.AddField(
            model_name="quotelineitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, help_text="Origin metadata (catalog reference)."),
        ),
        migrations.AlterField(
            model_name="quotelineitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Line-level discount as absolute amount (EUR).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="quotelineitem",
            name="qty",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantity (can be fractional).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="quotelineitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Tax rate as percentage (e.g. 20.00 for 20%).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotelineitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Unit price (in EUR). Use Decimal, not float.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Coalesce(
                                    models.F("subtotal"),
                                    models.Value(
                                        Decimal("0.00"), output_field=models.DecimalField(decimal_places=2, max_digits=12)
                                    ),
                                ),
                                "+",
                                django.db.models.functions.comparison.Coalesce(
                                    models.F("tax_total"),
                                    models.Value(
                                        Decimal("0.00"), output_field=models.DecimalField(decimal_places=2, max_digits=12)
                                    ),
                                ),
                            ),
                            "-",
                            django.db.models.functions.comparison.Coalesce(
                                models.F("discount_total"),
                                models.Value(
                                    Decimal("0.00"), output_field=models.DecimalField(decimal_places=2, max_digits=12)
                                ),
                            ),
                        ),
                    )
                ),
                name="ck_quote_totals_match",
            ),
        ),
    ]
