# Generated by Django 5.2.4 on 2025-09-21 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0002_alter_quotelineitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentterms",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="If null, this payment terms is global (available to all users).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentterms",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)), fields=("name",), name="uq_payment_global_name"
            ),
        ),
    ]
