# Generated by Django 5.2.4 on 2025-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0003_alter_paymentterms_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="reference",
            field=models.CharField(editable=False, help_text="Human-readable reference unique per owner.", max_length=64),
        ),
    ]
