# Generated by Django 5.2.4 on 2025-11-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0004_alter_quote_reference"),
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that owns this quote (replaces owner).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="user.account",
            ),
        ),
    ]
