# Generated by Django 5.2.4 on 2025-11-29

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    Populate Quote.account from owner.accounts.first().

    Assumes each user has at least one active account (created in Phase 3).
    """
    Quote = apps.get_model("quote", "Quote")
    Account = apps.get_model("user", "Account")

    for quote in Quote.objects.filter(account__isnull=True):
        # Get first active account for owner
        account = Account.objects.filter(user=quote.owner, is_active=True).first()

        if not account:
            # Fallback: get any account (even inactive)
            account = Account.objects.filter(user=quote.owner).first()

        if not account:
            raise ValueError(f"User {quote.owner_id} has no account. Run Phase 3 data migration first.")

        quote.account = account
        quote.save(update_fields=["account"])


def reverse_func(apps, schema_editor):
    """Rollback: clear account FK."""
    Quote = apps.get_model("quote", "Quote")
    Quote.objects.all().update(account=None)


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0005_add_account_fk"),
        ("user", "0010_migrate_professional_to_account"),  # Ensure Account data exists
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
