# Generated by Django 5.2.4 on 2025-11-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0006_migrate_to_account"),
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        # Make account NOT NULL (data already migrated in 0006)
        migrations.AlterField(
            model_name="quote",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="user.account",
                help_text="Account that owns this quote.",
            ),
        ),
    ]
