# Generated by Django 5.2.4 on 2025-11-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0007_account_not_null"),
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="account",
            field=models.ForeignKey(
                help_text="Account owning this quote.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="user.account",
            ),
        ),
    ]
