# Generated by Django 5.2.4 on 2025-12-13 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_add_field_encryption"),
        ("quote", "0008_alter_quote_account"),
        ("user", "0014_add_field_encryption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["account", "updated_at"], name="ix_quote_account_updated_at"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["account", "issue_date"], name="ix_quote_account_issue_date"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["account", "status"], name="ix_quote_account_status"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["account", "reference"], name="ix_quote_account_reference"),
        ),
    ]
