# Generated by Django 5.2.4 on 2025-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0009_quote_ix_quote_account_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="quotehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("sent", "Sent"),
                    ("status_changed", "Status changed"),
                    ("deleted", "Deleted"),
                ],
                max_length=32,
            ),
        ),
    ]
