# Generated by Django 5.2.4 on 2026-01-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0010_add_soft_delete_to_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotelineitem",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
