# Generated by Django 5.2.4 on 2026-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0011_alter_quotelineitem_description_to_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotelineitem",
            name="details",
            field=models.TextField(blank=True, default="", help_text="Optional detailed description for the line item."),
        ),
    ]
