# Generated by Django 5.2.4 on 2025-08-11 20:27

from django.db import migrations

def split_name(full_name: str):
    if not full_name:
        return "", ""
    parts = full_name.strip().split()
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], " ".join(parts[1:])

def forwards(apps, schema_editor):
    User = apps.get_model("user", "User")
    Profile = apps.get_model("user", "Profile")
    # si la table existe déjà, on ne la recrée pas : on peuple seulement
    for u in User.objects.all():
        # skip si un profil existe déjà (idempotence)
        if Profile.objects.filter(user_id=u.id).exists():
            continue
        first, last = split_name(getattr(u, "full_name", "") or "")
        Profile.objects.create(
            user_id=u.id,
            first_name=first,
            last_name=last,
            phone=(getattr(u, "phone", "") or ""),
            role="freelance",
        )

def backwards(apps, schema_editor):
    # no-op : on ne remonte pas
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_managers_profile"),
    ]

    operations = []
