# Generated by Django 5.2.4 on 2025-09-18 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("user", "0005_alter_user_options_user_uniq_user_email_ci"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status_juridique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("micro", "Micro-entrepreneur"),
                            ("eirl", "EIRL"),
                            ("eurl", "EURL"),
                            ("sasu", "SASU"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("tjm_cents", models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("number_pro", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domaine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professionals",
                        to="catalog.area",
                    ),
                ),
                ("service_types", models.ManyToManyField(blank=True, related_name="professionals", to="catalog.prestation")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="professional", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional user",
                "verbose_name_plural": "Professional users",
                "indexes": [
                    models.Index(fields=["domaine"], name="user_profes_domaine_38a4de_idx"),
                    models.Index(fields=["tjm_cents"], name="user_profes_tjm_cen_70a90d_idx"),
                ],
            },
        ),
    ]
