# Generated by Django 5.2.4 on 2025-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("user", "0006_professionaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaluser",
            name="allowed_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Areas supplémentaires dans lesquelles ce pro accepte de travailler (hors domaine principal).",
                related_name="allowed_professionals",
                to="catalog.area",
            ),
        ),
    ]
