# Generated by Django 5.2.4 on 2025-09-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_professionaluser_allowed_areas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionaluser",
            name="allowed_areas",
        ),
    ]
