# Generated by Django 5.2.4 on 2025-11-25 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_prestation_unique_area_prestation_name_and_more"),
        ("user", "0008_remove_professionaluser_allowed_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=255)),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("micro", "Micro-entrepreneur"),
                            ("eirl", "EIRL"),
                            ("eurl", "EURL"),
                            ("sasu", "SASU"),
                            ("other", "Autre"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("legal_id", models.CharField(blank=True, help_text="SIRET (14 digits)", max_length=14, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="catalog.area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="accounts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "indexes": [
                    models.Index(fields=["user"], name="user_accoun_user_id_32ff6e_idx"),
                    models.Index(fields=["domain"], name="user_accoun_domain__1bd39f_idx"),
                ],
                "unique_together": {("user", "display_name")},
            },
        ),
    ]
