# Generated by Django 5.2.4 on 2025-11-25 20:14

from django.db import migrations
from django.utils import timezone


def migrate_professional_to_account(apps, schema_editor):
    """Copy all ProfessionalUser records to Account model."""
    ProfessionalUser = apps.get_model("user", "ProfessionalUser")
    Account = apps.get_model("user", "Account")

    for prof in ProfessionalUser.objects.all():
        # Handle display_name: use name or fallback
        display_name = prof.name if prof.name else f"Account {prof.user_id}"

        # Handle legal_form: use status_juridique or default to micro
        legal_form = prof.status_juridique if prof.status_juridique else "micro"

        # Create Account from ProfessionalUser
        Account.objects.create(
            user_id=prof.user_id,
            display_name=display_name,
            legal_form=legal_form,
            legal_id=prof.number_pro,  # SIRET/TVA
            domain_id=prof.domaine_id,
            is_active=True,
            created_at=prof.created_at if prof.created_at else timezone.now(),
            updated_at=prof.updated_at if prof.updated_at else timezone.now(),
        )


def reverse_migration(apps, schema_editor):
    """Delete all Account records (rollback)."""
    Account = apps.get_model("user", "Account")
    Account.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_account"),
    ]

    operations = [
        migrations.RunPython(migrate_professional_to_account, reverse_migration),
    ]
