# Generated by Django 5.2.4 on 2025-11-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_migrate_professional_to_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.DeleteModel(
            name="ProfessionalUser",
        ),
    ]
