# Generated by Django 5.2.4 on 2025-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_prestation_unique_area_prestation_name_global"),
        ("user", "0011_cleanup_phase6"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="default_rate_cents",
            field=models.BigIntegerField(blank=True, help_text="Default daily rate in cents (TJM)", null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="service_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Favorite service types for this account",
                related_name="accounts_favorites",
                to="catalog.prestation",
            ),
        ),
    ]
