# Generated by Django 5.2.4 on 2025-12-11 07:38

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_add_soft_delete_to_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="legal_id",
            field=apps.core.fields.EncryptedCharField(blank=True, help_text="SIRET (14 digits)", null=True),
        ),
    ]
