# Generated by Django 5.2.4 on 2026-01-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_add_field_encryption"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="professional_headline",
            field=models.CharField(
                blank=True,
                help_text="Professional title displayed on quotes (e.g., 'Développeur Fullstack')",
                max_length=100,
                null=True,
            ),
        ),
    ]
