# Generated by Django 5.2.4 on 2026-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_add_professional_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="logo_url",
            field=models.URLField(blank=True, help_text="Company logo URL", null=True),
        ),
    ]
