# Generated by Django 5.2.4 on 2026-01-18 16:45

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_add_logo_url_to_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="address_line1",
            field=apps.core.fields.EncryptedCharField(blank=True, help_text="Street address line 1"),
        ),
        migrations.AddField(
            model_name="account",
            name="address_line2",
            field=apps.core.fields.EncryptedCharField(blank=True, help_text="Street address line 2"),
        ),
        migrations.AddField(
            model_name="account",
            name="city",
            field=apps.core.fields.EncryptedCharField(blank=True, help_text="City"),
        ),
        migrations.AddField(
            model_name="account",
            name="country",
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code", max_length=2),
        ),
        migrations.AddField(
            model_name="account",
            name="postal_code",
            field=apps.core.fields.EncryptedCharField(blank=True, help_text="Postal/ZIP code"),
        ),
    ]
