# Generated by Django 5.2.4 on 2026-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_add_account_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="max_clients",
            field=models.IntegerField(blank=True, help_text="Max total clients (None=unlimited)", null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="max_quotes_monthly",
            field=models.IntegerField(blank=True, help_text="Max quotes per month (None=unlimited)", null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="plan",
            field=models.CharField(
                choices=[("beta", "Beta (unlimited)"), ("free", "Free"), ("pro", "Pro")],
                default="beta",
                help_text="Subscription plan (beta=unlimited during beta phase)",
                max_length=10,
            ),
        ),
    ]
