# Generated by Django 5.2.4 on 2026-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_add_subscription_plan_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
