--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-18 14:39:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16548)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO fs_user;

--
-- TOC entry 218 (class 1259 OID 16551)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16552)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO fs_user;

--
-- TOC entry 220 (class 1259 OID 16555)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16556)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO fs_user;

--
-- TOC entry 222 (class 1259 OID 16559)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 25705)
-- Name: catalog_area; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.catalog_area (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(120) NOT NULL
);


ALTER TABLE public.catalog_area OWNER TO fs_user;

--
-- TOC entry 242 (class 1259 OID 25704)
-- Name: catalog_area_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.catalog_area ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_area_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 25713)
-- Name: catalog_prestation; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.catalog_prestation (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    name character varying(120) NOT NULL,
    description text NOT NULL,
    weight_days integer NOT NULL,
    default_rate_cents bigint NOT NULL,
    status character varying(20) NOT NULL,
    area_id bigint NOT NULL,
    CONSTRAINT catalog_prestation_weight_days_check CHECK ((weight_days >= 0)),
    CONSTRAINT prestation_rate_nonneg CHECK ((default_rate_cents >= 0)),
    CONSTRAINT prestation_weight_days_nonneg CHECK ((weight_days >= 0))
);


ALTER TABLE public.catalog_prestation OWNER TO fs_user;

--
-- TOC entry 244 (class 1259 OID 25712)
-- Name: catalog_prestation_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.catalog_prestation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_prestation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16560)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO fs_user;

--
-- TOC entry 224 (class 1259 OID 16566)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16567)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO fs_user;

--
-- TOC entry 226 (class 1259 OID 16570)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16571)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO fs_user;

--
-- TOC entry 228 (class 1259 OID 16576)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16577)
-- Name: django_session; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO fs_user;

--
-- TOC entry 239 (class 1259 OID 16709)
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO fs_user;

--
-- TOC entry 238 (class 1259 OID 16708)
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16715)
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO fs_user;

--
-- TOC entry 240 (class 1259 OID 16714)
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 35335)
-- Name: user_professionaluser; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_professionaluser (
    id bigint NOT NULL,
    name character varying(255),
    status_juridique character varying(20),
    tjm_cents bigint NOT NULL,
    number_pro character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    domaine_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_professionaluser OWNER TO fs_user;

--
-- TOC entry 246 (class 1259 OID 35334)
-- Name: user_professionaluser_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_professionaluser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_professionaluser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 35343)
-- Name: user_professionaluser_service_types; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_professionaluser_service_types (
    id bigint NOT NULL,
    professionaluser_id bigint NOT NULL,
    prestation_id bigint NOT NULL
);


ALTER TABLE public.user_professionaluser_service_types OWNER TO fs_user;

--
-- TOC entry 248 (class 1259 OID 35342)
-- Name: user_professionaluser_service_types_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_professionaluser_service_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_professionaluser_service_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16693)
-- Name: user_profile; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_profile (
    id bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    birthday date,
    phone character varying(20),
    avatar_url character varying(200),
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_profile OWNER TO fs_user;

--
-- TOC entry 236 (class 1259 OID 16692)
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16582)
-- Name: user_user; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(20)
);


ALTER TABLE public.user_user OWNER TO fs_user;

--
-- TOC entry 231 (class 1259 OID 16587)
-- Name: user_user_groups; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_user_groups OWNER TO fs_user;

--
-- TOC entry 232 (class 1259 OID 16590)
-- Name: user_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16591)
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16592)
-- Name: user_user_user_permissions; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_user_user_permissions OWNER TO fs_user;

--
-- TOC entry 235 (class 1259 OID 16595)
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5080 (class 0 OID 16548)
-- Dependencies: 217
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5082 (class 0 OID 16552)
-- Dependencies: 219
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5084 (class 0 OID 16556)
-- Dependencies: 221
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add profile	7	add_profile
26	Can change profile	7	change_profile
27	Can delete profile	7	delete_profile
28	Can view profile	7	view_profile
29	Can add Blacklisted Token	8	add_blacklistedtoken
30	Can change Blacklisted Token	8	change_blacklistedtoken
31	Can delete Blacklisted Token	8	delete_blacklistedtoken
32	Can view Blacklisted Token	8	view_blacklistedtoken
33	Can add Outstanding Token	9	add_outstandingtoken
34	Can change Outstanding Token	9	change_outstandingtoken
35	Can delete Outstanding Token	9	delete_outstandingtoken
36	Can view Outstanding Token	9	view_outstandingtoken
37	Can add Prestation	10	add_prestation
38	Can change Prestation	10	change_prestation
39	Can delete Prestation	10	delete_prestation
40	Can view Prestation	10	view_prestation
41	Can add Area	11	add_area
42	Can change Area	11	change_area
43	Can delete Area	11	delete_area
44	Can view Area	11	view_area
45	Can add Professional user	12	add_professionaluser
46	Can change Professional user	12	change_professionaluser
47	Can delete Professional user	12	delete_professionaluser
48	Can view Professional user	12	view_professionaluser
\.


--
-- TOC entry 5106 (class 0 OID 25705)
-- Dependencies: 243
-- Data for Name: catalog_area; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.catalog_area (id, created_at, updated_at, name) FROM stdin;
1	2025-08-29 16:04:55.289456+02	2025-08-29 16:04:55.28947+02	Développement web
2	2025-08-29 16:04:55.293579+02	2025-08-29 16:04:55.293589+02	Développement mobile
3	2025-08-29 16:04:55.294755+02	2025-08-29 16:04:55.294762+02	Développement de jeux vidéo
4	2025-08-29 16:04:55.295674+02	2025-08-29 16:04:55.29568+02	UI / UX Design
5	2025-08-29 16:04:55.296875+02	2025-08-29 16:04:55.29688+02	Data Science
6	2025-08-29 16:04:55.29766+02	2025-08-29 16:04:55.297664+02	Data Engineering
7	2025-08-29 16:04:55.298281+02	2025-08-29 16:04:55.298284+02	Cloud & DevOps
8	2025-08-29 16:04:55.298915+02	2025-08-29 16:04:55.298918+02	Cybersécurité
9	2025-08-29 16:04:55.299586+02	2025-08-29 16:04:55.29959+02	IA / Machine Learning
10	2025-08-29 16:04:55.300324+02	2025-08-29 16:04:55.300328+02	Marketing digital
11	2025-08-29 16:04:55.301076+02	2025-08-29 16:04:55.301081+02	SEO / Référencement
12	2025-08-29 16:04:55.30181+02	2025-08-29 16:04:55.301814+02	Rédaction de contenu
13	2025-08-29 16:04:55.302415+02	2025-08-29 16:04:55.302419+02	Copywriting
14	2025-08-29 16:04:55.303024+02	2025-08-29 16:04:55.303028+02	Community management
15	2025-08-29 16:04:55.303629+02	2025-08-29 16:04:55.303633+02	Communication
16	2025-08-29 16:04:55.304217+02	2025-08-29 16:04:55.30422+02	Brand design & identité
17	2025-08-29 16:04:55.304801+02	2025-08-29 16:04:55.304804+02	Design graphique
18	2025-08-29 16:04:55.305497+02	2025-08-29 16:04:55.305501+02	Illustration
19	2025-08-29 16:04:55.306244+02	2025-08-29 16:04:55.306248+02	Motion design
20	2025-08-29 16:04:55.306834+02	2025-08-29 16:04:55.306838+02	Photographie
21	2025-08-29 16:04:55.307416+02	2025-08-29 16:04:55.30742+02	Vidéo / Montage
22	2025-08-29 16:04:55.30801+02	2025-08-29 16:04:55.308013+02	Audio / Podcast
23	2025-08-29 16:04:55.308609+02	2025-08-29 16:04:55.308612+02	Traduction / Localisation
24	2025-08-29 16:04:55.30924+02	2025-08-29 16:04:55.309244+02	Product Management
25	2025-08-29 16:04:55.310338+02	2025-08-29 16:04:55.310342+02	Gestion de projet
26	2025-08-29 16:04:55.310959+02	2025-08-29 16:04:55.310963+02	Finance & Comptabilité
27	2025-08-29 16:04:55.311562+02	2025-08-29 16:04:55.311566+02	Juridique
28	2025-08-29 16:04:55.31215+02	2025-08-29 16:04:55.312154+02	RH & Recrutement
29	2025-08-29 16:04:55.31272+02	2025-08-29 16:04:55.312724+02	Formation & Coaching
30	2025-08-29 16:04:55.313286+02	2025-08-29 16:04:55.313289+02	Événementiel
31	2025-08-29 16:04:55.313834+02	2025-08-29 16:04:55.313837+02	Immobilier
32	2025-08-29 16:04:55.314393+02	2025-08-29 16:04:55.314397+02	Artisanat & Bâtiment
33	2025-08-29 16:04:55.315126+02	2025-08-29 16:04:55.315129+02	E-commerce
34	2025-08-29 16:04:55.3157+02	2025-08-29 16:04:55.315703+02	No-code / Low-code
35	2025-08-29 16:04:55.316414+02	2025-08-29 16:04:55.316418+02	Web3 / Blockchain
36	2025-08-29 16:04:55.317155+02	2025-08-29 16:04:55.317159+02	Santé & Bien-être
37	2025-08-29 16:04:55.317752+02	2025-08-29 16:04:55.317755+02	Publicité Réseaux Sociaux
38	2025-08-29 16:04:55.318334+02	2025-08-29 16:04:55.318337+02	CRM & Automatisation
\.


--
-- TOC entry 5108 (class 0 OID 25713)
-- Dependencies: 245
-- Data for Name: catalog_prestation; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.catalog_prestation (id, created_at, updated_at, is_deleted, deleted_at, name, description, weight_days, default_rate_cents, status, area_id) FROM stdin;
1	2025-08-29 16:09:59.871194+02	2025-08-29 16:09:59.871207+02	f	\N	Site vitrine	Création d’un site vitrine responsive (3–5 pages) avec CMS.	6	4500000	ACTIVE	1
2	2025-08-29 16:09:59.873812+02	2025-08-29 16:09:59.873817+02	f	\N	Portfolio développeur	Portfolio moderne avec section projets, blog et contact.	4	4200000	ACTIVE	1
3	2025-08-29 16:09:59.874962+02	2025-08-29 16:09:59.874966+02	f	\N	Refonte performance	Audit + optimisation Core Web Vitals et temps de chargement.	3	5000000	ACTIVE	1
4	2025-08-29 16:09:59.875944+02	2025-08-29 16:09:59.875948+02	f	\N	Boutique e‑commerce	Mise en place d’une boutique (catalogue, paiement, livraison).	8	5500000	ACTIVE	33
5	2025-08-29 16:09:59.876936+02	2025-08-29 16:09:59.87694+02	f	\N	App mobile MVP	Prototype fonctionnel (iOS/Android) avec 3 écrans clés.	10	6500000	ACTIVE	2
6	2025-08-29 16:09:59.87803+02	2025-08-29 16:09:59.878034+02	f	\N	App no‑code	Application interne via outils no‑code (Airtable/Glide/Notion).	3	3500000	ACTIVE	34
7	2025-08-29 16:09:59.880291+02	2025-08-29 16:09:59.880297+02	f	\N	Audit UX	Audit heuristique + rapport priorisé avec quick wins.	2	4800000	ACTIVE	4
8	2025-08-29 16:09:59.88185+02	2025-08-29 16:09:59.881856+02	f	\N	Maquettes haute fidélité	Maquettes Figma de 5 écrans clés + prototype cliquable.	4	5000000	ACTIVE	4
9	2025-08-29 16:09:59.883023+02	2025-08-29 16:09:59.883027+02	f	\N	Identité visuelle	Logo, couleurs, typographies et mini charte (10 pages).	5	4500000	ACTIVE	16
10	2025-08-29 16:09:59.884176+02	2025-08-29 16:09:59.884181+02	f	\N	Design system	Bibliothèque de composants (UI kit) documentée.	6	5200000	ACTIVE	17
11	2025-08-29 16:09:59.885288+02	2025-08-29 16:09:59.885292+02	f	\N	Dashboard BI	Création d’un tableau de bord (Power BI/Looker) connecté.	4	6000000	ACTIVE	5
12	2025-08-29 16:09:59.886442+02	2025-08-29 16:09:59.886446+02	f	\N	Pipeline de données	Ingestion + transformation + stockage (ETL) prêt à l’emploi.	7	7000000	ACTIVE	6
13	2025-08-29 16:09:59.887523+02	2025-08-29 16:09:59.887527+02	f	\N	PoC IA Générative	Prototype assisté IA pour un cas d’usage métier ciblé.	5	7500000	ACTIVE	9
14	2025-08-29 16:09:59.888518+02	2025-08-29 16:09:59.888522+02	f	\N	Infra as Code	Provisionnement cloud via Terraform + CI/CD de base.	5	6500000	ACTIVE	7
15	2025-08-29 16:09:59.889556+02	2025-08-29 16:09:59.88956+02	f	\N	Pentest applicatif	Test d’intrusion boîte grise + rapport de remédiation.	6	9000000	ACTIVE	8
16	2025-08-29 16:09:59.890551+02	2025-08-29 16:09:59.890555+02	f	\N	Stratégie marketing	Plan d’acquisition 90 jours, personas & parcours clients.	3	4000000	ACTIVE	10
17	2025-08-29 16:09:59.891501+02	2025-08-29 16:09:59.891505+02	f	\N	Audit SEO complet	Technique + contenu + netlinking avec backlog d’actions.	3	4200000	ACTIVE	11
18	2025-08-29 16:09:59.892443+02	2025-08-29 16:09:59.892446+02	f	\N	Campagne Meta Ads	Création et gestion d’une campagne publicitaire 30 jours.	2	3800000	ACTIVE	37
19	2025-08-29 16:09:59.893373+02	2025-08-29 16:09:59.893377+02	f	\N	Automatisation CRM	Scénarios d’emailing et scoring leads (HubSpot/Make).	4	5000000	ACTIVE	38
20	2025-08-29 16:09:59.894389+02	2025-08-29 16:09:59.894393+02	f	\N	Pack articles SEO (x4)	4 articles optimisés (1200–1500 mots) avec brief & méta.	5	3000000	ACTIVE	12
21	2025-08-29 16:09:59.895825+02	2025-08-29 16:09:59.895829+02	f	\N	Landing page copy	Copy conversion (USP, preuves, CTA) pour une landing.	2	3500000	ACTIVE	13
22	2025-08-29 16:09:59.896966+02	2025-08-29 16:09:59.89697+02	f	\N	Pitch deck	Deck 12–16 slides pour levée de fonds ou vente B2B.	3	4500000	ACTIVE	15
23	2025-08-29 16:09:59.898036+02	2025-08-29 16:09:59.89804+02	f	\N	Gestion réseaux (30j)	Calendrier éditorial + 12 posts + modération de base.	4	3200000	ACTIVE	14
24	2025-08-29 16:09:59.89931+02	2025-08-29 16:09:59.899314+02	f	\N	Shooting produit	Prises de vue packshot (jusqu’à 15 produits) + retouches.	2	4000000	ACTIVE	20
25	2025-08-29 16:09:59.900287+02	2025-08-29 16:09:59.90029+02	f	\N	Vidéo courte (reel)	Tournage + montage d’une vidéo 30–60 sec format vertical.	2	4200000	ACTIVE	21
26	2025-08-29 16:09:59.901234+02	2025-08-29 16:09:59.901238+02	f	\N	Montage podcast (x4)	Montage + habillage sonore pour 4 épisodes (20–30 min).	3	3000000	ACTIVE	22
27	2025-08-29 16:09:59.902541+02	2025-08-29 16:09:59.902551+02	f	\N	Atelier discovery	Atelier cadrage (problèmes, hypothèses, métriques).	1	6000000	ACTIVE	24
28	2025-08-29 16:09:59.903836+02	2025-08-29 16:09:59.903842+02	f	\N	PM à temps partiel (mois)	Pilotage projet 8 jours / mois avec cérémonies agiles.	8	5500000	ACTIVE	25
29	2025-08-29 16:09:59.905034+02	2025-08-29 16:09:59.905038+02	f	\N	Sprint recrutement	Sourcing + entretiens + short‑list pour un poste tech.	5	4000000	ACTIVE	28
30	2025-08-29 16:09:59.905996+02	2025-08-29 16:09:59.906+02	f	\N	Pack CGV + Mentions	Rédaction CGV, mentions légales, politique de confidentialité.	3	6500000	ACTIVE	27
31	2025-08-29 16:09:59.906958+02	2025-08-29 16:09:59.906962+02	f	\N	Prévisionnel financier	Budget, trésorerie, seuil de rentabilité sur 12 mois.	3	5000000	ACTIVE	26
32	2025-08-29 16:09:59.908081+02	2025-08-29 16:09:59.908085+02	f	\N	Organisation d’événement	Conception + logistique pour un événement B2B (50–100 pers.).	7	4500000	ACTIVE	30
33	2025-08-29 16:09:59.909148+02	2025-08-29 16:09:59.909153+02	f	\N	Visite virtuelle 3D	Capture et création d’une visite virtuelle d’un bien.	2	4200000	ACTIVE	31
34	2025-08-29 16:09:59.910232+02	2025-08-29 16:09:59.910236+02	f	\N	Plan 3D d’aménagement	Conception 3D d’un aménagement intérieur (une pièce).	2	3800000	ACTIVE	32
35	2025-08-29 16:09:59.911327+02	2025-08-29 16:09:59.911331+02	f	\N	Programme bien‑être 4 semaines	Plan d’entraînement + mobilité + habitudes.	2	2500000	ACTIVE	36
36	2025-08-29 16:09:59.912569+02	2025-08-29 16:09:59.912573+02	f	\N	Traduction FR↔EN (10k mots)	Traduction professionnnelle et relecture contextualisée.	5	2800000	ACTIVE	23
37	2025-08-29 16:09:59.913809+02	2025-08-29 16:09:59.913814+02	f	\N	Smart contract simple	Contrat ERC‑20 basique avec tests.	3	8000000	DRAFT	35
38	2025-08-29 16:09:59.914863+02	2025-08-29 16:09:59.914868+02	f	\N	Prototype jeu 2D	Prototype jouable (Godot/Unity) avec 1 niveau.	7	6000000	DRAFT	3
39	2025-08-29 16:09:59.915951+02	2025-08-29 16:09:59.915955+02	f	\N	Refonte branding complète	Rebranding global multi‑canal.	15	7000000	ARCHIVED	10
\.


--
-- TOC entry 5086 (class 0 OID 16560)
-- Dependencies: 223
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5088 (class 0 OID 16567)
-- Dependencies: 225
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	user	user
7	user	profile
8	token_blacklist	blacklistedtoken
9	token_blacklist	outstandingtoken
10	catalog	prestation
11	catalog	area
12	user	professionaluser
\.


--
-- TOC entry 5090 (class 0 OID 16571)
-- Dependencies: 227
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-07-31 09:40:34.058767+02
2	contenttypes	0002_remove_content_type_name	2025-07-31 09:40:34.063654+02
3	auth	0001_initial	2025-07-31 09:40:34.096124+02
4	auth	0002_alter_permission_name_max_length	2025-07-31 09:40:34.099023+02
5	auth	0003_alter_user_email_max_length	2025-07-31 09:40:34.1038+02
6	auth	0004_alter_user_username_opts	2025-07-31 09:40:34.106809+02
7	auth	0005_alter_user_last_login_null	2025-07-31 09:40:34.1096+02
8	auth	0006_require_contenttypes_0002	2025-07-31 09:40:34.110684+02
9	auth	0007_alter_validators_add_error_messages	2025-07-31 09:40:34.113633+02
10	auth	0008_alter_user_username_max_length	2025-07-31 09:40:34.116386+02
11	auth	0009_alter_user_last_name_max_length	2025-07-31 09:40:34.119282+02
12	auth	0010_alter_group_name_max_length	2025-07-31 09:40:34.123778+02
13	auth	0011_update_proxy_permissions	2025-07-31 09:40:34.12703+02
14	auth	0012_alter_user_first_name_max_length	2025-07-31 09:40:34.1299+02
15	user	0001_initial	2025-07-31 09:40:34.161825+02
16	admin	0001_initial	2025-07-31 09:40:34.177646+02
17	admin	0002_logentry_remove_auto_add	2025-07-31 09:40:34.181762+02
18	admin	0003_logentry_add_action_flag_choices	2025-07-31 09:40:34.187904+02
19	sessions	0001_initial	2025-07-31 09:40:34.198971+02
20	user	0002_remove_user_username_alter_user_email	2025-07-31 10:30:38.03798+02
21	user	0003_alter_user_managers_profile	2025-08-11 22:21:20.61506+02
22	user	0004_migrate_profile_data	2025-08-11 22:28:18.722483+02
23	token_blacklist	0001_initial	2025-08-12 22:32:52.737142+02
24	token_blacklist	0002_outstandingtoken_jti_hex	2025-08-12 22:32:52.743822+02
25	token_blacklist	0003_auto_20171017_2007	2025-08-12 22:32:52.748501+02
26	token_blacklist	0004_auto_20171017_2013	2025-08-12 22:32:52.756741+02
27	token_blacklist	0005_remove_outstandingtoken_jti	2025-08-12 22:32:52.766667+02
28	token_blacklist	0006_auto_20171017_2113	2025-08-12 22:32:52.772716+02
29	token_blacklist	0007_auto_20171017_2214	2025-08-12 22:32:52.796038+02
30	token_blacklist	0008_migrate_to_bigautofield	2025-08-12 22:32:52.818312+02
31	token_blacklist	0010_fix_migrate_to_bigautofield	2025-08-12 22:32:52.826423+02
32	token_blacklist	0011_linearizes_history	2025-08-12 22:32:52.82723+02
33	token_blacklist	0012_alter_outstandingtoken_user	2025-08-12 22:32:52.830779+02
34	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2025-08-12 22:32:52.838165+02
35	user	0005_alter_user_options_user_uniq_user_email_ci	2025-08-12 22:32:52.847889+02
36	catalog	0001_initial	2025-08-29 14:29:57.515855+02
37	user	0006_professionaluser	2025-09-18 11:46:17.598755+02
\.


--
-- TOC entry 5092 (class 0 OID 16577)
-- Dependencies: 229
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5102 (class 0 OID 16709)
-- Dependencies: 239
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2025-08-12 22:43:58.586432+02	2
2	2025-08-15 15:21:04.990577+02	5
\.


--
-- TOC entry 5104 (class 0 OID 16715)
-- Dependencies: 241
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTYzNTc3NiwiaWF0IjoxNzU1MDMwOTc2LCJqdGkiOiIzZjdmMjRmMGI1ZWU0YjM4YmQyYjRjNDA0ZGYxNjNmNSIsInVzZXJfaWQiOiI5In0.kQB78A5dNYvPBIgRCt08WeQtdF6HodtIzrJOWR0mHoI	2025-08-12 22:36:16.571845+02	2025-08-19 22:36:16+02	9	3f7f24f0b5ee4b38bd2b4c404df163f5
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTYzNjIwNiwiaWF0IjoxNzU1MDMxNDA2LCJqdGkiOiIyYzk1NTY5MzQ2ZDI0ZDZkODc1YWE1OGU4YjliNTNjNCIsInVzZXJfaWQiOiI5In0.4lx4m2hAMOrtdhpJRdNPnpC0ADddBsJ97QOl97i9eAM	2025-08-12 22:43:26.555756+02	2025-08-19 22:43:26+02	9	2c95569346d24d6d875aa58e8b9b53c4
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTc4NTg5MCwiaWF0IjoxNzU1MTgxMDkwLCJqdGkiOiI2ZDc5ODYxNDBjNWQ0MzM3ODgwNDdlNGVmOGU5MDQwMSIsInVzZXJfaWQiOiI5In0.LivDnggjnQ1lyVlP2GJCUpI0pnxE3oNVlz2rkqz7810	2025-08-14 16:18:10.023032+02	2025-08-21 16:18:10+02	9	6d7986140c5d433788047e4ef8e90401
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTc4NjQwOCwiaWF0IjoxNzU1MTgxNjA4LCJqdGkiOiJiNDgxOGNmODY3ZDg0MDBmYWY1YjA0YjhhODI1OWQ4MSIsInVzZXJfaWQiOiIxMCJ9.XpIGaDYaw5P8taC1hHfq5rI2QaySVlYRlmFWEu8hXy8	2025-08-14 16:26:48.948707+02	2025-08-21 16:26:48+02	10	b4818cf867d8400faf5b04b8a8259d81
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTg2ODgyMSwiaWF0IjoxNzU1MjY0MDIxLCJqdGkiOiI0OTQ3ZDljNzljOGM0YTFkOTFiY2IyODYxZWNlMjY2NiIsInVzZXJfaWQiOiIxMCJ9.Rq1-AAx9vcUmUcoc-EQ8TltyLQNsOvEx645iBNE2-Y8	2025-08-15 15:20:21.559473+02	2025-08-22 15:20:21+02	10	4947d9c79c8c4a1d91bcb2861ece2666
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTg2OTEzNiwiaWF0IjoxNzU1MjY0MzM2LCJqdGkiOiJmMTJlZWY1MjkxNzA0NzdlOWY5MTRkODdmYzc2NDMwNCIsInVzZXJfaWQiOiIxMCJ9.mEBOK8YR7q2cfXUmyyXeCFUjmxiI-PP12_mmvMqJrJU	2025-08-15 15:25:36.79718+02	2025-08-22 15:25:36+02	10	f12eef529170477e9f914d87fc764304
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODcwMTgxNSwiaWF0IjoxNzU4MDk3MDE1LCJqdGkiOiI3MDhmYWI2YmIwNzA0NzkwYTA4NWYzZTRkODQ0OTRmOCIsInVzZXJfaWQiOiI5In0.G_Qd9Z6b-DeDOQcRaOAc-3UgrSuRZfzDaoWUob5gPRc	2025-09-17 10:16:55.170651+02	2025-09-24 10:16:55+02	9	708fab6bb0704790a085f3e4d84494f8
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODcwODAzNiwiaWF0IjoxNzU4MTAzMjM2LCJqdGkiOiIxZTU2MGEzMzNkM2Q0NGY0YWQ1YzBiZTZhM2U5NjM3OCIsInVzZXJfaWQiOiI5In0.N5243rB9w84ZXrOMZ7xtT5Y_DQRbepUCK3H4iufSpbY	2025-09-17 12:00:36.053431+02	2025-09-24 12:00:36+02	9	1e560a333d3d44f4ad5c0be6a3e96378
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODc4NzA0OSwiaWF0IjoxNzU4MTgyMjQ5LCJqdGkiOiI4NjE1M2FjYmFmZDY0MzM5OTZmY2YxMzE3NDZmMTZlZiIsInVzZXJfaWQiOiI5In0.Nqb-aB-XczvGZ3x-Aw9SJ9ycux0h1_RbTqY32UOXM-U	2025-09-18 09:57:29.464082+02	2025-09-25 09:57:29+02	9	86153acbafd6433996fcf131746f16ef
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODc5MzE0NSwiaWF0IjoxNzU4MTg4MzQ1LCJqdGkiOiI4YThlMTMyZGRkOWU0ODUyODY5MzAyNTA1Y2MzOTVlYiIsInVzZXJfaWQiOiI5In0.eJk6His8w0PBvrn2IvZL1NyWQp7_YTsVdkxfVlQjoO0	2025-09-18 11:39:05.356856+02	2025-09-25 11:39:05+02	9	8a8e132ddd9e4852869302505cc395eb
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODc5MzU5NywiaWF0IjoxNzU4MTg4Nzk3LCJqdGkiOiIzZTgxYmUxMGZjMjg0Mjk5ODFlMzI0YzExZjI3MzY5ZiIsInVzZXJfaWQiOiI5In0.lUkGZY8uRjY5WKM8UpXhAC-p67CSgV3fIXmnwm6NcD8	2025-09-18 11:46:37.754247+02	2025-09-25 11:46:37+02	9	3e81be10fc28429981e324c11f27369f
\.


--
-- TOC entry 5110 (class 0 OID 35335)
-- Dependencies: 247
-- Data for Name: user_professionaluser; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_professionaluser (id, name, status_juridique, tjm_cents, number_pro, created_at, updated_at, domaine_id, user_id) FROM stdin;
1	Jean Jean Pro	micro	9036850	84641351	2025-09-18 11:47:45.882569+02	2025-09-18 11:49:24.354936+02	5	9
\.


--
-- TOC entry 5112 (class 0 OID 35343)
-- Dependencies: 249
-- Data for Name: user_professionaluser_service_types; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_professionaluser_service_types (id, professionaluser_id, prestation_id) FROM stdin;
1	1	2
\.


--
-- TOC entry 5100 (class 0 OID 16693)
-- Dependencies: 237
-- Data for Name: user_profile; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_profile (id, first_name, last_name, birthday, phone, avatar_url, role, created_at, updated_at, user_id) FROM stdin;
3	Jeanne	Dupont	1995-06-15	0712345678	\N	freelance	2025-08-11 23:01:57.381899+02	2025-08-11 23:01:57.381907+02	8
4	string	string	2025-08-12	string	\N	freelance	2025-08-12 22:34:45.573017+02	2025-08-12 22:34:45.573026+02	9
5	string	string	2025-08-14	string	\N	freelance	2025-08-14 16:25:55.63587+02	2025-08-14 16:25:55.635877+02	10
\.


--
-- TOC entry 5093 (class 0 OID 16582)
-- Dependencies: 230
-- Data for Name: user_user; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_user (id, password, last_login, is_superuser, first_name, last_name, email, is_staff, is_active, date_joined, full_name, phone) FROM stdin;
1	pbkdf2_sha256$1000000$aHFfgNv7wDCGqRGyN7icGH$5YL9NY73jGGd9n8Xk9vVk2AeTYk6qXXy2J12KxEX2W8=	\N	f			jean.dupont@example.com	f	t	2025-07-31 09:51:23.198157+02	Jean Dupont	0612345678
4	pbkdf2_sha256$1000000$eRNCD7VMgNn3VDni3AfJJs$VuILQe7LJ2/iYOKms4vavR36OQznW0tKNYPThZrLtNc=	\N	f			Jeaaaannnnne.dupont@example.com	f	t	2025-07-31 10:32:00.676107+02	Jeaaaannnnne Dupont	0712345678
8	pbkdf2_sha256$1000000$pQpnVP9H5kFj7lIS0syGAm$mt2853T9iJsUgt3i4CKKNQIIxXBs8RqmV22rE07Mx5g=	\N	f			jeanne@example.com	f	t	2025-08-11 23:01:57.115863+02		\N
9	pbkdf2_sha256$1000000$50DhnWJV9OUfQ2rjh1Gjhv$WtAVR6rh81nuq0Hde/K7P+J3yBSgydDZjieCMDKAoFk=	\N	f			user@example.com	f	t	2025-08-12 22:34:45.303511+02		\N
10	pbkdf2_sha256$1000000$oTEFbwWvUdbk1QTPJWg2ke$owSY3QL5MDcuGbWWPLndgOgANop9Yagebe7CkOClWAs=	\N	f			user2@example.com	f	t	2025-08-14 16:25:55.368094+02		\N
11	pbkdf2_sha256$1000000$caPq9qfTQfX1dIZDiwTBhl$nGIRMJTr2VH4p/zQ9ov5+FU1TnaWsgMT+xfC0CPWrFw=	\N	f			dbg@example.local	f	t	2025-09-17 11:55:27.065824+02		\N
12	pbkdf2_sha256$1000000$Zx1313yqxSrkGwobWEfCD4$gn3TVoUf+FJHTHDm0wMmxuk3MDkKhN7shdVPuUAloHo=	\N	f			dbg2@example.local	f	t	2025-09-17 11:57:31.824596+02		\N
\.


--
-- TOC entry 5094 (class 0 OID 16587)
-- Dependencies: 231
-- Data for Name: user_user_groups; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5097 (class 0 OID 16592)
-- Dependencies: 234
-- Data for Name: user_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 218
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5120 (class 0 OID 0)
-- Dependencies: 220
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5121 (class 0 OID 0)
-- Dependencies: 222
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- TOC entry 5122 (class 0 OID 0)
-- Dependencies: 242
-- Name: catalog_area_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.catalog_area_id_seq', 38, true);


--
-- TOC entry 5123 (class 0 OID 0)
-- Dependencies: 244
-- Name: catalog_prestation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.catalog_prestation_id_seq', 39, true);


--
-- TOC entry 5124 (class 0 OID 0)
-- Dependencies: 224
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5125 (class 0 OID 0)
-- Dependencies: 226
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 228
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 37, true);


--
-- TOC entry 5127 (class 0 OID 0)
-- Dependencies: 238
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 2, true);


--
-- TOC entry 5128 (class 0 OID 0)
-- Dependencies: 240
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 11, true);


--
-- TOC entry 5129 (class 0 OID 0)
-- Dependencies: 246
-- Name: user_professionaluser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_professionaluser_id_seq', 1, true);


--
-- TOC entry 5130 (class 0 OID 0)
-- Dependencies: 248
-- Name: user_professionaluser_service_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_professionaluser_service_types_id_seq', 1, true);


--
-- TOC entry 5131 (class 0 OID 0)
-- Dependencies: 236
-- Name: user_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_profile_id_seq', 5, true);


--
-- TOC entry 5132 (class 0 OID 0)
-- Dependencies: 232
-- Name: user_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_user_groups_id_seq', 1, false);


--
-- TOC entry 5133 (class 0 OID 0)
-- Dependencies: 233
-- Name: user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_user_id_seq', 12, true);


--
-- TOC entry 5134 (class 0 OID 0)
-- Dependencies: 235
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 4827 (class 2606 OID 16597)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4832 (class 2606 OID 16599)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4835 (class 2606 OID 16601)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4829 (class 2606 OID 16603)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4838 (class 2606 OID 16605)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4840 (class 2606 OID 16607)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 25711)
-- Name: catalog_area catalog_area_name_key; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.catalog_area
    ADD CONSTRAINT catalog_area_name_key UNIQUE (name);


--
-- TOC entry 4892 (class 2606 OID 25709)
-- Name: catalog_area catalog_area_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.catalog_area
    ADD CONSTRAINT catalog_area_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 25722)
-- Name: catalog_prestation catalog_prestation_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.catalog_prestation
    ADD CONSTRAINT catalog_prestation_pkey PRIMARY KEY (id);


--
-- TOC entry 4843 (class 2606 OID 16609)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 16611)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4848 (class 2606 OID 16613)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 16615)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4853 (class 2606 OID 16617)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4878 (class 2606 OID 16747)
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 4880 (class 2606 OID 16768)
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- TOC entry 4883 (class 2606 OID 16738)
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- TOC entry 4885 (class 2606 OID 16756)
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 25724)
-- Name: catalog_prestation unique_area_prestation_name; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.catalog_prestation
    ADD CONSTRAINT unique_area_prestation_name UNIQUE (area_id, name);


--
-- TOC entry 4909 (class 2606 OID 35339)
-- Name: user_professionaluser user_professionaluser_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser
    ADD CONSTRAINT user_professionaluser_pkey PRIMARY KEY (id);


--
-- TOC entry 4913 (class 2606 OID 35362)
-- Name: user_professionaluser_service_types user_professionaluser_se_professionaluser_id_pres_f78944bf_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser_service_types
    ADD CONSTRAINT user_professionaluser_se_professionaluser_id_pres_f78944bf_uniq UNIQUE (professionaluser_id, prestation_id);


--
-- TOC entry 4916 (class 2606 OID 35347)
-- Name: user_professionaluser_service_types user_professionaluser_service_types_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser_service_types
    ADD CONSTRAINT user_professionaluser_service_types_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 35341)
-- Name: user_professionaluser user_professionaluser_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser
    ADD CONSTRAINT user_professionaluser_user_id_key UNIQUE (user_id);


--
-- TOC entry 4874 (class 2606 OID 16699)
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 16701)
-- Name: user_profile user_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_user_id_key UNIQUE (user_id);


--
-- TOC entry 4858 (class 2606 OID 16689)
-- Name: user_user user_user_email_1c6f3d1a_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_email_1c6f3d1a_uniq UNIQUE (email);


--
-- TOC entry 4863 (class 2606 OID 16619)
-- Name: user_user_groups user_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 16621)
-- Name: user_user_groups user_user_groups_user_id_group_id_bb60391f_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_group_id_bb60391f_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4860 (class 2606 OID 16623)
-- Name: user_user user_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4869 (class 2606 OID 16625)
-- Name: user_user_user_permissions user_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 16627)
-- Name: user_user_user_permissions user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4825 (class 1259 OID 16630)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4830 (class 1259 OID 16631)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4833 (class 1259 OID 16632)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4836 (class 1259 OID 16633)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4887 (class 1259 OID 25725)
-- Name: catalog_area_created_at_e8ddfcd1; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_area_created_at_e8ddfcd1 ON public.catalog_area USING btree (created_at);


--
-- TOC entry 4888 (class 1259 OID 25727)
-- Name: catalog_area_name_2ab58fa4_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_area_name_2ab58fa4_like ON public.catalog_area USING btree (name varchar_pattern_ops);


--
-- TOC entry 4893 (class 1259 OID 25726)
-- Name: catalog_area_updated_at_cd5aab47; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_area_updated_at_cd5aab47 ON public.catalog_area USING btree (updated_at);


--
-- TOC entry 4894 (class 1259 OID 25738)
-- Name: catalog_prestation_area_id_53d84cfa; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_prestation_area_id_53d84cfa ON public.catalog_prestation USING btree (area_id);


--
-- TOC entry 4895 (class 1259 OID 25733)
-- Name: catalog_prestation_created_at_6cf99d38; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_prestation_created_at_6cf99d38 ON public.catalog_prestation USING btree (created_at);


--
-- TOC entry 4896 (class 1259 OID 25735)
-- Name: catalog_prestation_is_deleted_25e4001a; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_prestation_is_deleted_25e4001a ON public.catalog_prestation USING btree (is_deleted);


--
-- TOC entry 4899 (class 1259 OID 25736)
-- Name: catalog_prestation_status_72db82a4; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_prestation_status_72db82a4 ON public.catalog_prestation USING btree (status);


--
-- TOC entry 4900 (class 1259 OID 25737)
-- Name: catalog_prestation_status_72db82a4_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_prestation_status_72db82a4_like ON public.catalog_prestation USING btree (status varchar_pattern_ops);


--
-- TOC entry 4901 (class 1259 OID 25734)
-- Name: catalog_prestation_updated_at_a4fdd01c; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX catalog_prestation_updated_at_a4fdd01c ON public.catalog_prestation USING btree (updated_at);


--
-- TOC entry 4841 (class 1259 OID 16634)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4844 (class 1259 OID 16635)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4851 (class 1259 OID 16636)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4854 (class 1259 OID 16637)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4902 (class 1259 OID 25739)
-- Name: idx_prest_area_status; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX idx_prest_area_status ON public.catalog_prestation USING btree (area_id, status);


--
-- TOC entry 4881 (class 1259 OID 16739)
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- TOC entry 4886 (class 1259 OID 16736)
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- TOC entry 4855 (class 1259 OID 16779)
-- Name: uniq_user_email_ci; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE UNIQUE INDEX uniq_user_email_ci ON public.user_user USING btree (lower((email)::text));


--
-- TOC entry 4905 (class 1259 OID 35359)
-- Name: user_profes_domaine_38a4de_idx; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_profes_domaine_38a4de_idx ON public.user_professionaluser USING btree (domaine_id);


--
-- TOC entry 4906 (class 1259 OID 35360)
-- Name: user_profes_tjm_cen_70a90d_idx; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_profes_tjm_cen_70a90d_idx ON public.user_professionaluser USING btree (tjm_cents);


--
-- TOC entry 4907 (class 1259 OID 35358)
-- Name: user_professionaluser_domaine_id_8e176355; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_professionaluser_domaine_id_8e176355 ON public.user_professionaluser USING btree (domaine_id);


--
-- TOC entry 4914 (class 1259 OID 35373)
-- Name: user_professionaluser_serv_professionaluser_id_fed239dd; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_professionaluser_serv_professionaluser_id_fed239dd ON public.user_professionaluser_service_types USING btree (professionaluser_id);


--
-- TOC entry 4917 (class 1259 OID 35374)
-- Name: user_professionaluser_service_types_prestation_id_bf16323e; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_professionaluser_service_types_prestation_id_bf16323e ON public.user_professionaluser_service_types USING btree (prestation_id);


--
-- TOC entry 4856 (class 1259 OID 16690)
-- Name: user_user_email_1c6f3d1a_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_email_1c6f3d1a_like ON public.user_user USING btree (email varchar_pattern_ops);


--
-- TOC entry 4861 (class 1259 OID 16638)
-- Name: user_user_groups_group_id_c57f13c0; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_groups_group_id_c57f13c0 ON public.user_user_groups USING btree (group_id);


--
-- TOC entry 4864 (class 1259 OID 16639)
-- Name: user_user_groups_user_id_13f9a20d; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_groups_user_id_13f9a20d ON public.user_user_groups USING btree (user_id);


--
-- TOC entry 4867 (class 1259 OID 16640)
-- Name: user_user_user_permissions_permission_id_ce49d4de; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_user_permissions_permission_id_ce49d4de ON public.user_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4870 (class 1259 OID 16641)
-- Name: user_user_user_permissions_user_id_31782f58; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_user_permissions_user_id_31782f58 ON public.user_user_user_permissions USING btree (user_id);


--
-- TOC entry 4918 (class 2606 OID 16643)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4919 (class 2606 OID 16648)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4920 (class 2606 OID 16653)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4930 (class 2606 OID 25728)
-- Name: catalog_prestation catalog_prestation_area_id_53d84cfa_fk_catalog_area_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.catalog_prestation
    ADD CONSTRAINT catalog_prestation_area_id_53d84cfa_fk_catalog_area_id FOREIGN KEY (area_id) REFERENCES public.catalog_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4921 (class 2606 OID 16658)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4922 (class 2606 OID 16663)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4928 (class 2606 OID 16774)
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4929 (class 2606 OID 16740)
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_user_user; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_user_user FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4933 (class 2606 OID 35368)
-- Name: user_professionaluser_service_types user_professionaluse_prestation_id_bf16323e_fk_catalog_p; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser_service_types
    ADD CONSTRAINT user_professionaluse_prestation_id_bf16323e_fk_catalog_p FOREIGN KEY (prestation_id) REFERENCES public.catalog_prestation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4934 (class 2606 OID 35363)
-- Name: user_professionaluser_service_types user_professionaluse_professionaluser_id_fed239dd_fk_user_prof; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser_service_types
    ADD CONSTRAINT user_professionaluse_professionaluser_id_fed239dd_fk_user_prof FOREIGN KEY (professionaluser_id) REFERENCES public.user_professionaluser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4931 (class 2606 OID 35348)
-- Name: user_professionaluser user_professionaluser_domaine_id_8e176355_fk_catalog_area_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser
    ADD CONSTRAINT user_professionaluser_domaine_id_8e176355_fk_catalog_area_id FOREIGN KEY (domaine_id) REFERENCES public.catalog_area(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4932 (class 2606 OID 35353)
-- Name: user_professionaluser user_professionaluser_user_id_d02d39a7_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_professionaluser
    ADD CONSTRAINT user_professionaluser_user_id_d02d39a7_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4927 (class 2606 OID 16702)
-- Name: user_profile user_profile_user_id_8fdce8e2_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_user_id_8fdce8e2_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4923 (class 2606 OID 16668)
-- Name: user_user_groups user_user_groups_group_id_c57f13c0_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_group_id_c57f13c0_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4924 (class 2606 OID 16673)
-- Name: user_user_groups user_user_groups_user_id_13f9a20d_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_13f9a20d_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4925 (class 2606 OID 16678)
-- Name: user_user_user_permissions user_user_user_permi_permission_id_ce49d4de_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permi_permission_id_ce49d4de_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4926 (class 2606 OID 16683)
-- Name: user_user_user_permissions user_user_user_permissions_user_id_31782f58_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_31782f58_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-09-18 14:39:45

--
-- PostgreSQL database dump complete
--

