--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-07-31 10:52:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5012 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16548)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO fs_user;

--
-- TOC entry 218 (class 1259 OID 16551)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16552)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO fs_user;

--
-- TOC entry 220 (class 1259 OID 16555)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16556)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO fs_user;

--
-- TOC entry 222 (class 1259 OID 16559)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16560)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO fs_user;

--
-- TOC entry 224 (class 1259 OID 16566)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16567)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO fs_user;

--
-- TOC entry 226 (class 1259 OID 16570)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16571)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO fs_user;

--
-- TOC entry 228 (class 1259 OID 16576)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16577)
-- Name: django_session; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO fs_user;

--
-- TOC entry 230 (class 1259 OID 16582)
-- Name: user_user; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(20)
);


ALTER TABLE public.user_user OWNER TO fs_user;

--
-- TOC entry 231 (class 1259 OID 16587)
-- Name: user_user_groups; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_user_groups OWNER TO fs_user;

--
-- TOC entry 232 (class 1259 OID 16590)
-- Name: user_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16591)
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16592)
-- Name: user_user_user_permissions; Type: TABLE; Schema: public; Owner: fs_user
--

CREATE TABLE public.user_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_user_user_permissions OWNER TO fs_user;

--
-- TOC entry 235 (class 1259 OID 16595)
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fs_user
--

ALTER TABLE public.user_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4988 (class 0 OID 16548)
-- Dependencies: 217
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 4990 (class 0 OID 16552)
-- Dependencies: 219
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 4992 (class 0 OID 16556)
-- Dependencies: 221
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
\.


--
-- TOC entry 4994 (class 0 OID 16560)
-- Dependencies: 223
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 4996 (class 0 OID 16567)
-- Dependencies: 225
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	user	user
\.


--
-- TOC entry 4998 (class 0 OID 16571)
-- Dependencies: 227
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-07-31 09:40:34.058767+02
2	contenttypes	0002_remove_content_type_name	2025-07-31 09:40:34.063654+02
3	auth	0001_initial	2025-07-31 09:40:34.096124+02
4	auth	0002_alter_permission_name_max_length	2025-07-31 09:40:34.099023+02
5	auth	0003_alter_user_email_max_length	2025-07-31 09:40:34.1038+02
6	auth	0004_alter_user_username_opts	2025-07-31 09:40:34.106809+02
7	auth	0005_alter_user_last_login_null	2025-07-31 09:40:34.1096+02
8	auth	0006_require_contenttypes_0002	2025-07-31 09:40:34.110684+02
9	auth	0007_alter_validators_add_error_messages	2025-07-31 09:40:34.113633+02
10	auth	0008_alter_user_username_max_length	2025-07-31 09:40:34.116386+02
11	auth	0009_alter_user_last_name_max_length	2025-07-31 09:40:34.119282+02
12	auth	0010_alter_group_name_max_length	2025-07-31 09:40:34.123778+02
13	auth	0011_update_proxy_permissions	2025-07-31 09:40:34.12703+02
14	auth	0012_alter_user_first_name_max_length	2025-07-31 09:40:34.1299+02
15	user	0001_initial	2025-07-31 09:40:34.161825+02
16	admin	0001_initial	2025-07-31 09:40:34.177646+02
17	admin	0002_logentry_remove_auto_add	2025-07-31 09:40:34.181762+02
18	admin	0003_logentry_add_action_flag_choices	2025-07-31 09:40:34.187904+02
19	sessions	0001_initial	2025-07-31 09:40:34.198971+02
20	user	0002_remove_user_username_alter_user_email	2025-07-31 10:30:38.03798+02
\.


--
-- TOC entry 5000 (class 0 OID 16577)
-- Dependencies: 229
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5001 (class 0 OID 16582)
-- Dependencies: 230
-- Data for Name: user_user; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_user (id, password, last_login, is_superuser, first_name, last_name, email, is_staff, is_active, date_joined, full_name, phone) FROM stdin;
1	pbkdf2_sha256$1000000$aHFfgNv7wDCGqRGyN7icGH$5YL9NY73jGGd9n8Xk9vVk2AeTYk6qXXy2J12KxEX2W8=	\N	f			jean.dupont@example.com	f	t	2025-07-31 09:51:23.198157+02	Jean Dupont	0612345678
4	pbkdf2_sha256$1000000$eRNCD7VMgNn3VDni3AfJJs$VuILQe7LJ2/iYOKms4vavR36OQznW0tKNYPThZrLtNc=	\N	f			Jeaaaannnnne.dupont@example.com	f	t	2025-07-31 10:32:00.676107+02	Jeaaaannnnne Dupont	0712345678
\.


--
-- TOC entry 5002 (class 0 OID 16587)
-- Dependencies: 231
-- Data for Name: user_user_groups; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5005 (class 0 OID 16592)
-- Dependencies: 234
-- Data for Name: user_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: fs_user
--

COPY public.user_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5013 (class 0 OID 0)
-- Dependencies: 218
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5014 (class 0 OID 0)
-- Dependencies: 220
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5015 (class 0 OID 0)
-- Dependencies: 222
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 24, true);


--
-- TOC entry 5016 (class 0 OID 0)
-- Dependencies: 224
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5017 (class 0 OID 0)
-- Dependencies: 226
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 6, true);


--
-- TOC entry 5018 (class 0 OID 0)
-- Dependencies: 228
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- TOC entry 5019 (class 0 OID 0)
-- Dependencies: 232
-- Name: user_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_user_groups_id_seq', 1, false);


--
-- TOC entry 5020 (class 0 OID 0)
-- Dependencies: 233
-- Name: user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_user_id_seq', 4, true);


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 235
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fs_user
--

SELECT pg_catalog.setval('public.user_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 4789 (class 2606 OID 16597)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4794 (class 2606 OID 16599)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4797 (class 2606 OID 16601)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4791 (class 2606 OID 16603)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4800 (class 2606 OID 16605)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4802 (class 2606 OID 16607)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4805 (class 2606 OID 16609)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 16611)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4810 (class 2606 OID 16613)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 16615)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4815 (class 2606 OID 16617)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4819 (class 2606 OID 16689)
-- Name: user_user user_user_email_1c6f3d1a_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_email_1c6f3d1a_uniq UNIQUE (email);


--
-- TOC entry 4824 (class 2606 OID 16619)
-- Name: user_user_groups user_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4827 (class 2606 OID 16621)
-- Name: user_user_groups user_user_groups_user_id_group_id_bb60391f_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_group_id_bb60391f_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4821 (class 2606 OID 16623)
-- Name: user_user user_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4830 (class 2606 OID 16625)
-- Name: user_user_user_permissions user_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4833 (class 2606 OID 16627)
-- Name: user_user_user_permissions user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq; Type: CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4787 (class 1259 OID 16630)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4792 (class 1259 OID 16631)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4795 (class 1259 OID 16632)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4798 (class 1259 OID 16633)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4803 (class 1259 OID 16634)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4806 (class 1259 OID 16635)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4813 (class 1259 OID 16636)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4816 (class 1259 OID 16637)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4817 (class 1259 OID 16690)
-- Name: user_user_email_1c6f3d1a_like; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_email_1c6f3d1a_like ON public.user_user USING btree (email varchar_pattern_ops);


--
-- TOC entry 4822 (class 1259 OID 16638)
-- Name: user_user_groups_group_id_c57f13c0; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_groups_group_id_c57f13c0 ON public.user_user_groups USING btree (group_id);


--
-- TOC entry 4825 (class 1259 OID 16639)
-- Name: user_user_groups_user_id_13f9a20d; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_groups_user_id_13f9a20d ON public.user_user_groups USING btree (user_id);


--
-- TOC entry 4828 (class 1259 OID 16640)
-- Name: user_user_user_permissions_permission_id_ce49d4de; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_user_permissions_permission_id_ce49d4de ON public.user_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4831 (class 1259 OID 16641)
-- Name: user_user_user_permissions_user_id_31782f58; Type: INDEX; Schema: public; Owner: fs_user
--

CREATE INDEX user_user_user_permissions_user_id_31782f58 ON public.user_user_user_permissions USING btree (user_id);


--
-- TOC entry 4834 (class 2606 OID 16643)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4835 (class 2606 OID 16648)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4836 (class 2606 OID 16653)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4837 (class 2606 OID 16658)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4838 (class 2606 OID 16663)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4839 (class 2606 OID 16668)
-- Name: user_user_groups user_user_groups_group_id_c57f13c0_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_group_id_c57f13c0_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4840 (class 2606 OID 16673)
-- Name: user_user_groups user_user_groups_user_id_13f9a20d_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_13f9a20d_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4841 (class 2606 OID 16678)
-- Name: user_user_user_permissions user_user_user_permi_permission_id_ce49d4de_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permi_permission_id_ce49d4de_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4842 (class 2606 OID 16683)
-- Name: user_user_user_permissions user_user_user_permissions_user_id_31782f58_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fs_user
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_31782f58_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-07-31 10:52:53

--
-- PostgreSQL database dump complete
--

